// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0tnrtUnr_qQpvEv_eHXGqn76JdZdJL4',
    appId: '1:117987681189:web:708890472859afba42be4c',
    messagingSenderId: '117987681189',
    projectId: 'fbs-auth-riverpod',
    authDomain: 'fbs-auth-riverpod.firebaseapp.com',
    storageBucket: 'fbs-auth-riverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcclh1_7i97EkmGTWJtO44r1l9Yuod03s',
    appId: '1:117987681189:android:817f8f7168a0903c42be4c',
    messagingSenderId: '117987681189',
    projectId: 'fbs-auth-riverpod',
    storageBucket: 'fbs-auth-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlxFdUFJ-DjQ_2DONzu9VN3p1W5E4cbDY',
    appId: '1:117987681189:ios:f8654825eb0b858642be4c',
    messagingSenderId: '117987681189',
    projectId: 'fbs-auth-riverpod',
    storageBucket: 'fbs-auth-riverpod.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlxFdUFJ-DjQ_2DONzu9VN3p1W5E4cbDY',
    appId: '1:117987681189:ios:f8654825eb0b858642be4c',
    messagingSenderId: '117987681189',
    projectId: 'fbs-auth-riverpod',
    storageBucket: 'fbs-auth-riverpod.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

}